<?php

namespace ContainerBbNApzO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AppContactController::deleteContact' => ['privates', '.service_locator.eZ8U3w0', 'get_ServiceLocator_EZ8U3w0Service', true],
            'App\\Controller\\AppContactController::readContact' => ['privates', '.service_locator.eZ8U3w0', 'get_ServiceLocator_EZ8U3w0Service', true],
            'App\\Controller\\AppFAQController::activate' => ['privates', '.service_locator.fTrb1el', 'get_ServiceLocator_FTrb1elService', true],
            'App\\Controller\\AppFAQController::delete' => ['privates', '.service_locator.fTrb1el', 'get_ServiceLocator_FTrb1elService', true],
            'App\\Controller\\AppFAQController::editFAQ' => ['privates', '.service_locator.fTrb1el', 'get_ServiceLocator_FTrb1elService', true],
            'App\\Controller\\BlogController::activate' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController::editBlogPost' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController::historique' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController::oldPost' => ['privates', '.service_locator.FwGxq_n', 'get_ServiceLocator_FwGxqNService', true],
            'App\\Controller\\BlogController::preview' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController::undo' => ['privates', '.service_locator.yyOfSkA', 'get_ServiceLocator_YyOfSkAService', true],
            'App\\Controller\\CategorieController::activate' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\CategorieController::editCategorie' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::activate' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController::editUser' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AppContactController:deleteContact' => ['privates', '.service_locator.eZ8U3w0', 'get_ServiceLocator_EZ8U3w0Service', true],
            'App\\Controller\\AppContactController:readContact' => ['privates', '.service_locator.eZ8U3w0', 'get_ServiceLocator_EZ8U3w0Service', true],
            'App\\Controller\\AppFAQController:activate' => ['privates', '.service_locator.fTrb1el', 'get_ServiceLocator_FTrb1elService', true],
            'App\\Controller\\AppFAQController:delete' => ['privates', '.service_locator.fTrb1el', 'get_ServiceLocator_FTrb1elService', true],
            'App\\Controller\\AppFAQController:editFAQ' => ['privates', '.service_locator.fTrb1el', 'get_ServiceLocator_FTrb1elService', true],
            'App\\Controller\\BlogController:activate' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController:editBlogPost' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController:historique' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController:oldPost' => ['privates', '.service_locator.FwGxq_n', 'get_ServiceLocator_FwGxqNService', true],
            'App\\Controller\\BlogController:preview' => ['privates', '.service_locator.cYpLFu1', 'get_ServiceLocator_CYpLFu1Service', true],
            'App\\Controller\\BlogController:undo' => ['privates', '.service_locator.yyOfSkA', 'get_ServiceLocator_YyOfSkAService', true],
            'App\\Controller\\CategorieController:activate' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\CategorieController:editCategorie' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:activate' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\UserController:editUser' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AppContactController::deleteContact' => '?',
            'App\\Controller\\AppContactController::readContact' => '?',
            'App\\Controller\\AppFAQController::activate' => '?',
            'App\\Controller\\AppFAQController::delete' => '?',
            'App\\Controller\\AppFAQController::editFAQ' => '?',
            'App\\Controller\\BlogController::activate' => '?',
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\BlogController::editBlogPost' => '?',
            'App\\Controller\\BlogController::historique' => '?',
            'App\\Controller\\BlogController::oldPost' => '?',
            'App\\Controller\\BlogController::preview' => '?',
            'App\\Controller\\BlogController::undo' => '?',
            'App\\Controller\\CategorieController::activate' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::editCategorie' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::activate' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::editUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AppContactController:deleteContact' => '?',
            'App\\Controller\\AppContactController:readContact' => '?',
            'App\\Controller\\AppFAQController:activate' => '?',
            'App\\Controller\\AppFAQController:delete' => '?',
            'App\\Controller\\AppFAQController:editFAQ' => '?',
            'App\\Controller\\BlogController:activate' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\BlogController:editBlogPost' => '?',
            'App\\Controller\\BlogController:historique' => '?',
            'App\\Controller\\BlogController:oldPost' => '?',
            'App\\Controller\\BlogController:preview' => '?',
            'App\\Controller\\BlogController:undo' => '?',
            'App\\Controller\\CategorieController:activate' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:editCategorie' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:activate' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:editUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
