<?php

namespace ContainerBbNApzO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppFAQFormTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\AppFAQFormType' shared autowired service.
     *
     * @return \App\Form\AppFAQFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AppFAQFormType'] = new \App\Form\AppFAQFormType();
    }
}
