<?php

namespace ContainerBbNApzO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppContactRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\AppContactRepository' shared autowired service.
     *
     * @return \App\Repository\AppContactRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AppContactRepository'] = new \App\Repository\AppContactRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
