<?php

namespace ContainerBbNApzO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\CategorieController' shared autowired service.
     *
     * @return \App\Controller\CategorieController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CategorieController'] = $instance = new \App\Controller\CategorieController(($container->privates['App\\Repository\\CategorieRepository'] ?? $container->load('getCategorieRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.HKQJjJV'] ?? $container->load('get_ServiceLocator_HKQJjJVService'))->withContext('App\\Controller\\CategorieController', $container));

        return $instance;
    }
}
