<?php

namespace ContainerBbNApzO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParamsFormTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\ParamsFormType' shared autowired service.
     *
     * @return \App\Form\ParamsFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ParamsFormType'] = new \App\Form\ParamsFormType();
    }
}
