<?php

namespace ContainerBbNApzO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParamsRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\ParamsRepository' shared autowired service.
     *
     * @return \App\Repository\ParamsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ParamsRepository'] = new \App\Repository\ParamsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
