<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBbNApzO\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBbNApzO/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerBbNApzO.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerBbNApzO\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerBbNApzO\App_KernelDevContainer([
    'container.build_hash' => 'BbNApzO',
    'container.build_id' => '9ac94109',
    'container.build_time' => 1706287209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBbNApzO');
